version: "3.7"
name: auth_service_sprint_1

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-api
      - movies-api

  auth-api:
    build: auth-service
    container_name: auth-api
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - .env.example

  movies-api:
    build: movies_api
    container_name: movies-api
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - redis
    expose:
      - "8000"
    env_file:
      - .env.example

  django:
    container_name: django
    env_file: "etc/environs/django.env"
    build: django_api
    restart: on-failure
    volumes:
      - ./django_api/static:/opt/app/static:ro

  etl-service:
    build: postgres_to_elastic
    container_name: postgres_to_elastic
    restart: unless-stopped
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - sqlite-to-postgres
    env_file:
      - .env.example

  sqlite-to-postgres:
    build: sqlite_to_postgres
    container_name: sqlite-to-postgres
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env.example
    expose:
      - "8010"

  postgres:
    image: postgres:13
    volumes:
      - ./init_postgres.sh:/docker-custom-entrypoint/init.sh
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./schema_design/scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env.example
    expose:
      - "5432"
    restart: unless-stopped

  redis:
    image: redis:latest
    expose:
      - "6379"
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
    volumes:
      - ./elastic_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - "9200"
    restart: unless-stopped